### ISSUE TITLE
 pull access denied for personapi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by joanmarcriera** [prasadbdvr/personapi#1]
Dear personapi maintainer, I reached the following error:

```bash 
 $ docker-compose -f src/main/docker/app.yml up -d
Pulling personapi-app (personapi:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling personapi-app (personapi:)...
ERROR: pull access denied for personapi, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
✘-1 ~/Downloads/hiring-EBI01705/personapi [master|✔]

```

Best regards
Marc

**Comment by prasadbdvr** [comment]
Hi Marc,
 I will look into this and get back to you.   Hope You can run below
command to run in Development mode for quick verification.

## Development

To start your application in the dev profile, run:

```
./mvnw
```

Regards,
Durga.

**Comment by prasadbdvr** [comment]
Hi Marc,
Hope You are not missed below command before you run
docker-compose command.  I am not missed


```
./mvnw -Pprod verify jib:dockerBuild
```
Note: above command create docker image locally

FYI, I am not seeing docker image pull issues on my local setup.

Regards,
Durga.

**Comment by joanmarcriera** [comment]
Hi Durga,

that is the point, I don't have mvnw in my environment. ;)


Best regards
Marc

**Comment by prasadbdvr** [comment]
Hi Marc,
I have pushed an image to my personal docker hub account and also updated
the image name in my github repo.  Please pull the code from my git
repository and run docker command

github repo: https://github.com/prasadbdvr/personapi.git
docker command: docker-compose -f src/main/docker/app.yml up -d
Regards,
Durga.

**Comment by joanmarcriera** [comment]
Hi, 

Sorry is taking so long, thanks for the update, and I'll be closing this issue. 
I'm moving you to the next stage (internal stage), good luck. 

If you like you can review a bit you docker knowledge, will not have an impact on your progress but I think you will benefit of working without using docker compose.

Thank you . 

Best regards
Marc

**Comment by prasadbdvr** [comment]
Thank You Marc.
Regards,
Durga prasad.
